// lib/mock-data.js
// Replace each section with real API calls once your OpenClaw gateway is live.

export const gatewayStatus = {
  online: true,
  mode: 'VPS',          // 'VPS' | 'LOCAL' | 'OFFLINE'
  vpsUrl: 'https://147.93.XX.XX:8080',
  latencyMs: 42,
  uptime: '14d 6h 22m',
  version: '2.4.1',
  lastPing: new Date().toISOString(),
  cpu: 18,
  ram: 43,
  disk: 27,
  activeSessions: 7,
  activeAgents: 5,
  queueDepth: 12,
};

export const activeAgents = [
  { id: 'mika',     label: 'Mika',     status: 'running', project: 'managed-by-mika',  task: 'Processing 3 guest check-in requests',  model: 'gpt-4o',            tokens: 84200  },
  { id: 'diamond',  label: 'Diamond',  status: 'running', project: 'digital-diamond',  task: 'Drafting AI audit proposal for TechCo',  model: 'gpt-4o',            tokens: 121000 },
  { id: 'twin',     label: 'Twin',     status: 'running', project: 'ai-twin',          task: 'Generating IG Reels scripts × 10',        model: 'claude-3-5-sonnet', tokens: 56300  },
  { id: 'recovery', label: 'Recovery', status: 'idle',    project: 'lead-recovery',    task: 'Waiting for next cron window (14:00)',     model: 'gpt-4o-mini',       tokens: 9800   },
  { id: 'medbot',   label: 'MedBot',   status: 'running', project: 'medai',            task: 'Handling 2 inbound scheduling calls',      model: 'gpt-4o-mini',       tokens: 34100  },
  { id: 'hookr',    label: 'Hookr',    status: 'paused',  project: 'hotel-hooker',     task: 'Awaiting approval: post_to_social',        model: 'claude-3-5-sonnet', tokens: 44500  },
  { id: 'cannabot', label: 'CannaBot', status: 'error',   project: 'cannaops',         task: 'FAILED: Leafly API rate limit exceeded',   model: 'gpt-4o-mini',       tokens: 2100   },
];

export const pendingApprovals = [
  {
    id: 'apr-001',
    agent: 'Hookr',
    project: 'hotel-hooker',
    action: 'post_to_social',
    summary: 'Post 4 Instagram stories promoting weekend availability — Hotel Hooker brand',
    content: 'Weekend suites are calling your name 💋 DM us to book your escape. Limited rooms, zero judgment.',
    createdAt: new Date(Date.now() - 18 * 60000).toISOString(),
    priority: 'high',
    channel: 'Instagram',
  },
  {
    id: 'apr-002',
    agent: 'Twin',
    project: 'ai-twin',
    action: 'publish_content',
    summary: 'Publish 3 TikTok scripts to content calendar as scheduled posts',
    content: 'Script batch: "AI does my job for a week" series — Episodes 4, 5, 6',
    createdAt: new Date(Date.now() - 47 * 60000).toISOString(),
    priority: 'medium',
    channel: 'TikTok',
  },
  {
    id: 'apr-003',
    agent: 'Diamond',
    project: 'digital-diamond',
    action: 'send_email_blast',
    summary: 'Send cold outreach to 87 vetted leads from Apollo list',
    content: 'Subject: "Your competitors are already using AI — are you?"',
    createdAt: new Date(Date.now() - 95 * 60000).toISOString(),
    priority: 'high',
    channel: 'Email',
  },
  {
    id: 'apr-004',
    agent: 'Recovery',
    project: 'lead-recovery',
    action: 'whatsapp_broadcast',
    summary: 'Send reactivation WhatsApp sequence to 31 cold leads (>60 days)',
    content: 'Hey [name], we worked together last year and I wanted to check in...',
    createdAt: new Date(Date.now() - 210 * 60000).toISOString(),
    priority: 'low',
    channel: 'WhatsApp',
  },
];

export const missionQueue = [
  { id: 'mq-01', time: '08:00', status: 'done',    label: 'Morning agent health checks',             project: null              },
  { id: 'mq-02', time: '09:00', status: 'done',    label: 'Pull overnight analytics — all brands',   project: 'digital-diamond' },
  { id: 'mq-03', time: '10:00', status: 'done',    label: 'Review Mika guest requests',              project: 'managed-by-mika' },
  { id: 'mq-04', time: '11:00', status: 'running', label: 'AI Twin: batch Reel scripts (10)',         project: 'ai-twin'         },
  { id: 'mq-05', time: '12:00', status: 'pending', label: 'Approve Hookr Instagram stories',         project: 'hotel-hooker'    },
  { id: 'mq-06', time: '13:00', status: 'pending', label: 'CannaOps: refresh Leafly inventory sync', project: 'cannaops'        },
  { id: 'mq-07', time: '14:00', status: 'pending', label: 'Lead Recovery: WhatsApp broadcast',       project: 'lead-recovery'   },
  { id: 'mq-08', time: '15:00', status: 'pending', label: 'MedAI: EOD scheduling report',            project: 'medai'           },
  { id: 'mq-09', time: '16:00', status: 'pending', label: 'Diamond: proposal delivery review',       project: 'digital-diamond' },
  { id: 'mq-10', time: '18:00', status: 'pending', label: 'Journal & daily debrief generation',      project: null              },
];

export const taskOutputs = [
  {
    id: 'out-001',
    agent: 'Diamond',
    project: 'digital-diamond',
    type: 'document',
    title: 'AI Audit Proposal Draft — TechCo Inc.',
    preview: 'Deliverable: 12-page AI readiness audit covering infrastructure, workflow gaps, and a 90-day automation roadmap. Estimated value: $8,500.',
    ts: new Date(Date.now() - 22 * 60000).toISOString(),
    status: 'ready_for_review',
  },
  {
    id: 'out-002',
    agent: 'Mika',
    project: 'managed-by-mika',
    type: 'action',
    title: 'Guest Check-in × 3 Processed',
    preview: 'Check-ins confirmed for rooms 204, 311, 408. Early arrival granted for 311. Welcome messages sent via WhatsApp.',
    ts: new Date(Date.now() - 35 * 60000).toISOString(),
    status: 'complete',
  },
  {
    id: 'out-003',
    agent: 'MedBot',
    project: 'medai',
    type: 'report',
    title: 'Morning Appointment Schedule Confirmed',
    preview: '14 appointments locked for Dr. Chen. 2 cancellations auto-filled from waitlist. 1 insurance query escalated to staff.',
    ts: new Date(Date.now() - 60 * 60000).toISOString(),
    status: 'complete',
  },
  {
    id: 'out-004',
    agent: 'Twin',
    project: 'ai-twin',
    type: 'content',
    title: 'TikTok Script Batch — "AI Does My Job" Ep 4-6',
    preview: 'Three 45-sec scripts generated. Hook strength score: 8.4/10. CTA tested across 3 variations. Ready for Hookr review.',
    ts: new Date(Date.now() - 90 * 60000).toISOString(),
    status: 'awaiting_approval',
  },
];

export const weeklyMetrics = [
  { day: 'Mon', tasks: 42, approvals: 8,  revenue: 1200 },
  { day: 'Tue', tasks: 58, approvals: 12, revenue: 2400 },
  { day: 'Wed', tasks: 51, approvals: 6,  revenue: 1800 },
  { day: 'Thu', tasks: 67, approvals: 15, revenue: 3100 },
  { day: 'Fri', tasks: 44, approvals: 9,  revenue: 2200 },
  { day: 'Sat', tasks: 29, approvals: 4,  revenue: 800  },
  { day: 'Sun', tasks: 38, approvals: 7,  revenue: 1400 },
];

export const goals = [
  {
    id: 'g-01',
    category: 'Revenue',
    title: 'Hit $25k MRR across all brands',
    progress: 62,
    target: 25000,
    current: 15500,
    unit: '$',
    deadline: '2024-12-31',
    brand: null,
  },
  {
    id: 'g-02',
    category: 'Digital Diamond',
    title: 'Close 5 new AI audit clients',
    progress: 40,
    target: 5,
    current: 2,
    unit: 'clients',
    deadline: '2024-10-31',
    brand: 'digital-diamond',
  },
  {
    id: 'g-03',
    category: 'AI Twin',
    title: 'Reach 10k TikTok followers',
    progress: 78,
    target: 10000,
    current: 7800,
    unit: 'followers',
    deadline: '2024-11-30',
    brand: 'ai-twin',
  },
  {
    id: 'g-04',
    category: 'MedAI',
    title: 'Onboard 3 medical practice clients',
    progress: 33,
    target: 3,
    current: 1,
    unit: 'practices',
    deadline: '2024-12-31',
    brand: 'medai',
  },
  {
    id: 'g-05',
    category: 'Lead Recovery',
    title: 'Reactivate 50 cold leads',
    progress: 56,
    target: 50,
    current: 28,
    unit: 'leads',
    deadline: '2024-10-15',
    brand: 'lead-recovery',
  },
];

export const journalEntries = [
  {
    id: 'j-001',
    date: new Date().toISOString().split('T')[0],
    mood: 'focused',
    title: 'Today\'s Debrief',
    body: 'Diamond proposal is looking sharp — need to tighten the pricing section. Mika handled the early check-ins beautifully, zero intervention required. CannaBot Leafly issue needs to be investigated before tomorrow\'s inventory run. Twin content is flowing well this week.',
    tags: ['digital-diamond', 'ai-twin', 'cannaops'],
    aiSummary: 'High productivity day. 3 of 5 active agents operating autonomously. 1 error requiring manual fix. Overall: on track.',
  },
  {
    id: 'j-002',
    date: new Date(Date.now() - 86400000).toISOString().split('T')[0],
    mood: 'winning',
    title: 'Thursday Recap',
    body: 'Closed the TechCo call. They want a full AI audit + implementation roadmap. If this converts, it\'ll be the largest Diamond engagement yet. Recovery workflow sent 31 WhatsApp messages — 7 replies so far, 2 booked calls.',
    tags: ['digital-diamond', 'lead-recovery'],
    aiSummary: 'Strong sales day. New opportunity worth $12-15k in pipeline. Lead recovery showing 22% reply rate.',
  },
];

export const memoryVault = [
  {
    id: 'mv-001',
    category: 'Client',
    title: 'TechCo Inc — AI Audit Scope',
    tags: ['digital-diamond', 'proposal', 'client'],
    content: 'CEO: Marcus Webb. Budget: $8k-$15k. Pain: too many manual handoffs in ops. Timeline: wants to start Q4. Decision maker, no procurement delays. Prefers async comms.',
    lastAccessed: new Date(Date.now() - 3600000).toISOString(),
    source: 'Obsidian',
  },
  {
    id: 'mv-002',
    category: 'System',
    title: 'OpenClaw Gateway — Docker Compose Notes',
    tags: ['technical', 'infrastructure'],
    content: 'Gateway runs on port 8080. Redis on 6379. Workers scale to 8 max. Use OPENCLAW_ENV=production. Restart policy: always. Health endpoint: /api/health.',
    lastAccessed: new Date(Date.now() - 7200000).toISOString(),
    source: 'Manual',
  },
  {
    id: 'mv-003',
    category: 'Brand',
    title: 'Hotel Hooker — Brand Voice Guide',
    tags: ['hotel-hooker', 'brand', 'content'],
    content: 'Tone: Cheeky, unapologetic, luxury sex-positive. Audience: liberated adults 28-45. Never: judgmental, explicit, or graphic. Always: witty, aspirational, clever double-entendres. Colors: midnight black + blush rose.',
    lastAccessed: new Date(Date.now() - 14400000).toISOString(),
    source: 'Google Drive',
  },
  {
    id: 'mv-004',
    category: 'Process',
    title: 'Lead Recovery — WhatsApp Sequence SOP',
    tags: ['lead-recovery', 'whatsapp', 'process'],
    content: 'Day 0: Warm reactivation message. Day 3: Value-add (case study). Day 7: Soft CTA. Day 14: Final check-in. If no reply after Day 14: archive & tag "truly cold".',
    lastAccessed: new Date(Date.now() - 86400000).toISOString(),
    source: 'Obsidian',
  },
];

export const prompts = [
  {
    id: 'pr-001',
    title: 'AI Audit Discovery Call Prep',
    category: 'Sales',
    project: 'digital-diamond',
    tags: ['sales', 'discovery', 'audit'],
    preview: 'You are a senior AI consultant preparing for a discovery call. Given the prospect company name and industry, generate 10 intelligent discovery questions that uncover automation gaps, tech stack weaknesses, and ROI opportunities...',
    uses: 47,
    rating: 4.9,
  },
  {
    id: 'pr-002',
    title: 'Guest Welcome Message (Luxury Tone)',
    category: 'Hospitality',
    project: 'managed-by-mika',
    tags: ['guest', 'welcome', 'hospitality'],
    preview: 'You are Mika, a warm and professional AI property manager. Write a personalized check-in welcome message for {{guest_name}} staying in {{room_type}}. Mention local dining, confirm Wi-Fi, and include a warm but not excessive sign-off...',
    uses: 203,
    rating: 4.8,
  },
  {
    id: 'pr-003',
    title: 'TikTok Hook Generator — Personal Brand',
    category: 'Content',
    project: 'ai-twin',
    tags: ['tiktok', 'hook', 'content', 'viral'],
    preview: 'Generate 5 TikTok video hooks for a solopreneur who runs AI-powered businesses. Each hook must create curiosity, hint at a transformation, and be under 8 seconds when spoken. Use pattern interrupts...',
    uses: 88,
    rating: 4.7,
  },
  {
    id: 'pr-004',
    title: 'Cold Lead Reactivation — WhatsApp',
    category: 'Lead Recovery',
    project: 'lead-recovery',
    tags: ['whatsapp', 'cold', 'reactivation', 'sales'],
    preview: 'You are a warm, non-pushy business owner following up with a lead who went cold {{days}} days ago. Write a WhatsApp message that feels personal, references {{last_touchpoint}}, and offers genuine value before any ask...',
    uses: 134,
    rating: 4.6,
  },
];

export const contentTasks = [
  {
    id: 'ct-001',
    project: 'ai-twin',
    type: 'video',
    title: 'TikTok: "AI Does My Job" — Episode 7',
    status: 'scripting',
    platform: 'TikTok',
    due: new Date(Date.now() + 86400000).toISOString(),
    assignedTo: 'Twin',
  },
  {
    id: 'ct-002',
    project: 'hotel-hooker',
    type: 'social',
    title: 'Instagram Stories — Weekend Promo (4 slides)',
    status: 'pending_approval',
    platform: 'Instagram',
    due: new Date(Date.now() + 3600000).toISOString(),
    assignedTo: 'Hookr',
  },
  {
    id: 'ct-003',
    project: 'digital-diamond',
    type: 'email',
    title: 'Apollo Outreach Sequence — Tech Founders List',
    status: 'pending_approval',
    platform: 'Email',
    due: new Date(Date.now() + 7200000).toISOString(),
    assignedTo: 'Diamond',
  },
  {
    id: 'ct-004',
    project: 'cannaops',
    type: 'report',
    title: 'Weekly Compliance Digest — State Regs Update',
    status: 'generating',
    platform: 'Internal',
    due: new Date(Date.now() + 172800000).toISOString(),
    assignedTo: 'CannaBot',
  },
];

export const leadMetrics = {
  totalCold:     156,
  contacted:      89,
  replied:        31,
  booked:         12,
  converted:       4,
  revenueRecover: 8400,
  channels: [
    { name: 'WhatsApp', sent: 47, replied: 14, rate: 29.8 },
    { name: 'Email',    sent: 31, replied:  9, rate: 29.0 },
    { name: 'Telegram', sent: 11, replied:  8, rate: 72.7 },
  ],
};

export const cannaOpsData = {
  dispensaries: 3,
  activeLocations: ['Miami Beach', 'Fort Lauderdale', 'Boca Raton'],
  complianceStatus: 'green',
  inventorySync: 'stale',
  lastSync: new Date(Date.now() - 3600000 * 5).toISOString(),
  topProducts: [
    { name: 'Blue Dream Flower (3.5g)', sku: 'BD-35', stock: 148, velocity: 'high'   },
    { name: 'OG Kush Pre-Rolls (2pk)', sku: 'OG-PR', stock:  34, velocity: 'medium' },
    { name: 'Mango Haze Vape Cart',    sku: 'MH-VC', stock:   7, velocity: 'low'    },
  ],
  pendingRegs: 2,
  dailyRevenue: 4820,
};

export const medAIData = {
  practices: 1,
  practiceNames: ['Chen Family Medicine'],
  todayAppointments: 14,
  waitlistFilled: 2,
  callsHandled: 9,
  escalated: 1,
  avgHandleTimeSec: 47,
  patientSatisfaction: 4.8,
  insuranceQueries: 3,
};
